#!/usr/bin/python
# -*- coding: utf-8 -*-
# strategy.strategy.py

'''
@summary: The Strategy class's goal is to generate a list of signals for
          one or several symbols based in inputs bars from
          a DataHandler object.
'''

# General imports
from abc import ABCMeta, abstractmethod


class Strategy(object):

    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) Strategy object is to generate Signal
    objects for particular symbols based on the inputs of Bars
    (OHLCV) generated by a DataHandler object.

    This is designed to work both with historic and live data as
    the Strategy object is agnostic to where the data came from,
    since it obtains the bar tuples from a queue object.
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def calculate_signals(self):
        """
        Provides the mechanisms to calculate the list of signals.
        """
        raise NotImplementedError("Should implement calculate_signals()")
    
    @abstractmethod
    def dump_updown_count(self):
        """
        Dump the count for movement up and down.
        """
        raise NotImplementedError("Should implement dump_updown_count()")
    